baseURL : 'https://cognivibes.github.io/'
languageCode : 'en-us'
theme : 'PaperMod'
paginate: 5
title : 'cogniVibes'
description : "Ayush's Blog"
author : 'Ayush Saha'

params:

  label:
    text: "cogniVibes"
    icon: cognivibes.png
  env: production  
  assets:
      favicon: "favicon.ico"
      favicon16x16: "favicon-16x16.png"
      favicon32x32: "favicon-32x32.png"
      apple_touch_icon: "apple-touch-icon.png"
      android_chrome192x192: "android-chrome-192x192.png"
      android_chrome512x512: "android-chrome-512x512.png"

  # defaultTheme: light
  # defaultTheme: dark
  defaultTheme: auto # to switch between dark or light according to browser theme
  disableThemeToggle: false

  homeInfoParams:
      Title: "[~]$ whoami?"
      image:
        url: gb.png
        title: cogniVibes
      Content: |
        - cogniVibes is my personal corner of the web. Here, I share my thoughts on a diverse range of topics, from the digital realm to the cinematic universe and everything in between. 
        - ***- Ayush Saha***
        -
        - New post every time I upload 😉

  socialIcons:
    - name: mastodon
      url: https://mastodon.social/@cogniVibes
    - name: dev
      url: https://dev.to/cognivibes
    - name: github
      url: https://github.com/cogniVibes
    - name: email
      url: https://cognivibes.github.io/about/#contact-me
    - name: rss
      url: https://cognivibes.github.io/index.xml

  # profileMode:
  #       enabled: true
  #       title: "[~]$ whoami?" # optional default will be site title
  #       subtitle: |
  #         I am Ayush Saha, a high school student (JEE Aspirant) from West Bengal, India.
  #         I enjoy coding, reading, and writing in my free time.
  #         The purpose of this website is to share my hobbies and ideas with people around the world. So if you have stumbled upon my website, please feel free to explore and learn more.
  #       imageUrl: ayush.png # optional
  #       imageTitle: "That's me right there" # optional
  #       imageWidth: 180 # custom size
  #       imageHeight: 180 # custom size
  #       buttons:
  #         - name: Programming
  #           url: "/programming"
  #         - name: Musings
  #           url: "/musings"

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false
  editPost:
      URL: "mailto:ayushsahaaltacc@gmail.com?subject=Suggesting changes to an article. "
      Text: Suggest Changes

  services:
    disqus:
      shortname: your-disqus-shortname

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 2
    keys: 
      - title
      - permalink
      - summary
      - content

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

menu:
  main:
    - name: Dev
      url: /dev/
      weight: 1

    - name: Musings
      url: /musings/
      weight: 2

    - name: About
      url: /about/
      weight: 6

    - name: Archive
      url: archives/
      weight: 3

    - name: Search
      url: search/
      weight: 4

    - name: Tags
      url: tags/
      weight: 5
